name: Style

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read
  packages: read

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository_owner }}/zurg-ci:latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Install format dependencies
        run: pip3 install clang-format==14.0.6 cmake_format==0.6.11 pyyaml

      - name: configure
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: check style
        run: cmake --build build --target check-format
