name: Ubuntu

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

permissions:
  contents: read
  packages: write

env:
  CTEST_OUTPUT_ON_FAILURE: 1
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  ci-image:
    uses: ./.github/workflows/ci-image.yml
    secrets: inherit

  build:
    needs: ci-image
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.ci-image.outputs.image }}

    steps:
      - uses: actions/checkout@v3

      - name: Align workspace path for coverage tools
        run: |
          if [ ! -e /home/runner/work ]; then
            mkdir -p /home/runner
            ln -s /__w /home/runner/work
          fi

      - uses: actions/cache@v3
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: Configure project
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: Configure tests
        run: cmake -S test -B test/build -DENABLE_TEST_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug

      - name: Build tests
        run: cmake --build test/build

      - name: Test
        run: ctest --output-on-failure --test-dir test/build

      - name: Coverage report
        run: |
          mkdir -p coverage
          gcovr -r ${{ github.workspace }} \
            --object-directory test/build \
            --txt coverage/summary.txt \
            --xml coverage/coverage.xml \
            --html-details coverage/index.html \
            --filter ".*/source/zurg/.*" \
            --exclude 'third_party/.*' \
            --exclude 'test/build/generated/.*' \
            --exclude 'standalone/.*' \
            --exclude 'test/source/.*' \
            --gcov-ignore-errors no_working_dir_found \
            --gcov-ignore-errors source_not_found \
            --fail-under-line 90

      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: collect code coverage
        run: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
